### ISSUE TITLE
Improve kubernetes release process

### ISSUE THREAD

**Issue by chuckha** [kubernetes/release#609] opened 2018-08-08 21:48 UTC
# How Release Works

The master branch of the release repo is used to build and release the expected kubernetes packages. The release project will checkout various versions of kubernetes, build the artifacts and release them. 

## The Problem

kubectl, kubeadm, kubelet, and any other rpm/deb package built by the release process suffers from being coupled with the release process and not the code it is building.

The problem with the build and release process being coupled is that different artifacts are built based on the code version, but the release process that defines part of the build is always the same for all versions being built. This causes errors such as v1.8.15 depending on cri-tools when v1.8.15 does not have any of the code necessary to make this dependency make sense. 

## Moving forward

I would like to start collecting information about the blockers for making bazel build process in kubernetes/kubernetes the canonical source.

<hr />

Improving packaging is out of scope for this ticket. I want to focus this ticket on the release process.

cc @kubernetes/sig-cluster-lifecycle-pr-reviews @tpepper

**Comment by ixdy** [comment] 2018-08-08 22:33
One of the main blockers is that we don't have a good story for multiarch compilation with cgo under bazel. This isn't particularly problematic for kubectl or kubeadm, but kubelet needs cgo.

**Comment by ixdy** [comment] 2018-08-08 22:33
cc @filbranden

**Comment by stealthybox** [comment] 2018-08-09 18:28
Discussed during **[kubeadm office-hours: Wed, 8 Aug 2018](https://docs.google.com/document/d/130_kiXjG7graFNSnIAgtMS1G8zPDwpkshgfRYS0nggo/edit#heading=h.n3je34ry58kt)** ([ recording ](https://youtu.be/pfcFaoyLDZs))

**Comment by timothysc** [comment] 2018-08-18 13:46
@ixdy - Is there a canonical bazel issue we can track and follow up on?

**Comment by ixdy** [comment] 2018-08-21 01:02
for bazel + cgo, probably https://github.com/bazelbuild/rules_go/issues/1020 or https://github.com/bazelbuild/rules_go/issues/1642.

I don't think there's a mondo-issue for kubernetes + bazel specifically.

**Comment by ixdy** [comment] 2018-11-26 19:56
https://github.com/kubernetes/community/blob/master/contributors/devel/bazel.md#known-issues-and-limitations has been recently updated with all of the current known-to-me issues.

**Comment by luxas** [comment] 2018-12-04 16:17
@ixdy so that is basically saying we can't compile release binaries with bazel in a long time?
Is it possible to "just" use bazel to create multiarch debs from already-made binaries from the other build scripts we have? Already that'd be progress.

**Comment by ixdy** [comment] 2018-12-04 22:56
yeah, we could probably use bazel as a heavyweight deb/rpm builder, relying on the built artifacts to exist already, adding a ["local repository"](https://docs.bazel.build/versions/master/be/workspace.html#local_repository) to `_output/dockerized` or something like that ...

**Comment by neolit123** [comment] 2019-03-01 01:57
multi arch from bazal is up:
https://github.com/kubernetes/kubernetes/pull/73930
https://github.com/kubernetes/kubernetes/pull/74468

we also have this tracking issue in k/k that seems like a duplicate of this one:
https://github.com/kubernetes/kubernetes/issues/71677

KEP for the decouple is up:
https://github.com/kubernetes/enhancements/pull/858

@chuckha please free to re-open this one.
thanks.
/close

**Closed by neolit123** 2019-03-01 01:57 UTC
Labels: sig/cluster-lifecycle
