### ISSUE TITLE
release note tool, link formatting in v1.19 release note page

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/release#1712] opened 2020-11-11 03:29 UTC
#### What happened:
The generated v1.19 release notes contain incorrect links (404).

#### What you expected to happen:
Update the release note tool to generate links in Markdown format.

#### How to reproduce it (as minimally and precisely as possible):
Review the v1.19 release notes page. There are several links that are incorrect.
One example at line 2444,
```
- CustomResourceDefinition schemas that use `x-kubernetes-list-map-keys` to specify properties that uniquely identify list items must make those properties required or have a default value, to ensure those properties are present for all list items. See https://kubernetes.io/docs/reference/using-api/api-concepts/&#35;merge-strategy for details. ([#88076](https://github.com/kubernetes/kubernetes/pull/88076), [@eloyekunle](https://github.com/eloyekunle)) [SIG API Machinery and Testing]
```

#### Anything else we need to know?:
For more information, see PR https://github.com/kubernetes/website/pull/24567 .

**Comment by saschagrunert** [comment] 2020-11-11 09:00
Confirmed, the issue exists because we're replacing all `#` there:
https://github.com/kubernetes/release/blob/65be49faa158b38a02cd263895c6726cf91a99ba/pkg/notes/notes.go#L342
 
/priority important-soon

**Comment by saschagrunert** [comment] 2020-11-11 09:18
Fix is incoming in https://github.com/kubernetes/release/pull/1715

**Closed** 2020-11-13 08:02 UTC
Labels: area/release-eng, kind/bug, priority/important-soon, sig/release
