### ISSUE TITLE
Packages for Ubuntu 18.04

### ISSUE THREAD

**Issue by dawidmalina** [kubernetes/release#589] opened 2018-07-19 06:23 UTC
Ubuntu 18.04 is available for a while but kubernetes packages are not available. When we can expect those packages?

**Comment by evanrich** [comment] 2018-07-20 21:14
was wondering the same thing myself.

**Comment by dawidmalina** [comment] 2018-07-30 20:00
Any updates on this? CC @ixdy @mikedanese

**Comment by ixdy** [comment] 2018-07-31 22:11
this is kinda a dupe of https://github.com/kubernetes/release/issues/589

**Comment by ixdy** [comment] 2018-07-31 22:13
this is kind of a dupe of https://github.com/kubernetes/kubernetes/issues/66300

**Comment by ixdy** [comment] 2018-08-09 01:18
also a dupe of #589.
/close

**Closed by ixdy** 2018-08-09 01:18 UTC
