### ISSUE TITLE
Do not write the /etc/default/kubelet file when installing kubelet/kubeadm packages

### ISSUE THREAD

**Issue by chuckha** [kubernetes/release#654] opened 2018-11-30 16:58 UTC
This file exists for users to customize. We don't need to write it as systemd does not require it ([see this discussion](https://github.com/kubernetes/kubernetes/issues/70489#issuecomment-443267375)) and we should never overwrite it.

**Comment by steven-sheehy** [comment] 2018-11-30 17:01
Also, the /etc/sysconfig/kubelet for RPM based distros.

**Comment by neolit123** [comment] 2018-11-30 21:19
i think not writing the file by default should be the right thing to do.
should be user created and we should only read but not write.

> Also, the /etc/sysconfig/kubelet for RPM based distros.

these kind of descrapencies are really bad.
i though things like the https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard
solved them.

**Comment by neolit123** [comment] 2019-02-28 21:41
/remove-lifecycle stale

@chuckha 
this merged for RPM:
https://github.com/kubernetes/release/pull/658

this comment claims that it's not needed on debian:
https://github.com/kubernetes/release/pull/658/files#r257808744

**Comment by steven-sheehy** [comment] 2019-02-28 21:55
@neolit123 It is true that debian marks files under /etc as conf files, but whether to overwrite or not if both files changed is [determined](https://www.debian.org/doc/debian-policy/ap-pkg-conffiles.html#automatic-handling-of-configuration-files-by-dpkg) by an interactive prompt to the user by default. This will of course fail if updating non-interactively via scripts unless you supply your preference version using `-y -o Dpkg::Options::="--force-confnew"`.

So it's better to not package the `/etc/default/kubelet` at all for debian.

**Comment by neolit123** [comment] 2019-02-28 22:00
sending PR in a bit.

**Comment by steven-sheehy** [comment] 2019-02-28 22:14
@neolit123 I think kubernetes/kubernetes#70489 can be closed as duplicate of this.

**Closed** 2019-02-28 22:59 UTC
