### ISSUE TITLE
Make it possible to build a patch release without building a Beta

### ISSUE THREAD

**Issue by davidopp** [kubernetes/release#154] opened 2016-10-16 08:20 UTC
@jessfraz noticed when building 1.4.3 that the release scripts also built a 1.4.4-beta0. Assuming that building the beta slows down the overall process (i.e. these are not completely identical), it would be good to have a "fast" mode that skips the beta when you're in a rush.

cc/ @janetkuo

**Comment by davidopp** [comment] 2016-10-16 08:30
And even if they are identical, it pushes them separately, which makes it take more time. So there is definitely *some* time to be saved by being able to only build one release.

**Comment by david-mcmahon** [comment] 2016-10-16 19:35
This is by (original) design.  It's possible to skip the beta builds in those cases, but we'd have to turn off the consumers too.  I believe GKE has some automated rollouts and expect there to be a beta.0 when a  new X.Y.Z official release is cut.  @alex-mohr @roberthbailey

**Comment by roberthbailey** [comment] 2016-10-17 02:31
1.4.4-beta.0 is a tag that we apply immediately after cutting a 1.4.3 release. This keeps the semantic name on the 1.4 release branch when testing CI builds *ahead* of 1.4.3 so that everything being tested at that point follows the correct semantic versioning rules. AFAIK it's just a tag applied to git which takes no extra time.

@zmerlynn

**Comment by davidopp** [comment] 2016-10-17 05:55
I think @jessfraz said that the release script pushes the patch release and beta release separately. I might be mis-remembering though.

**Comment by jessfraz** [comment] 2016-10-17 06:24
I builds the artifacts and pushes them to gcr and gcs for both the major
release and the beta.

**Comment by roberthbailey** [comment] 2016-10-17 06:41
That must have changed with the release automation.

**Comment by david-mcmahon** [comment] 2016-10-17 19:28
@roberthbailey the betas have always been pushed at the same time as the official. 
Before the automation was in place and I was still doing things manually, I forgot to push a beta once and got a stern talking to from Ike.  Apparently it broke the GKE CI.  I don't know if that requirement is still in place, but if not we certainly could skip building and publishing betas.

**Comment by david-mcmahon** [comment] 2016-10-22 20:52
So again, this is a very simple change on the release side.  The issue is making sure we're not breaking anyone.

**Comment by david-mcmahon** [comment] 2017-05-03 20:20
Closing this.  There is the larger issue of what downstream (GKE) expects before anything can happen with this task.

**Closed by david-mcmahon** 2017-05-03 20:20 UTC
Labels: priority/P3

**Comment by david-mcmahon** [comment] 2017-09-06 20:11
@ihmccreery Can you add some context here?  I remember one time before the automation (anago), we didn't push one of these tagged (but unreleased) releases and something fell over.  What was that again and is that still the case today?
